# Generated by Django 4.1.7 on 2023-03-23 21:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_remove_book_authors_book_authors'),
    ]

    operations = [
        migrations.AddField(
            model_name='author',
            name='avatar',
            field=models.ImageField(default='avatar.jpg', null=True, upload_to=''),
        ),
    ]
